SELECT *
FROM ((SELECT NEWS_ID, TITLE, SHORT_TEXT,
            FULL_TEXT, CREATION_DATE, MODIFICATION_DATE, COMMENTS_COUNT
       FROM NEWS JOIN (SELECT NEWS_ID, COUNT(*) COMMENTS_COUNT
                       FROM COMMENTS
                       GROUP BY NEWS_ID) NEWS_STAT USING(NEWS_ID))
UNION
(SELECT NEWS_ID, TITLE, SHORT_TEXT,
            FULL_TEXT, CREATION_DATE, MODIFICATION_DATE, 0 COMMENTS_COUNT
FROM NEWS
WHERE NEWS_ID NOT IN(SELECT NEWS_ID
                     FROM COMMENTS))) ALL_NEWS_STAT
WHERE EXISTS(SELECT * FROM NEWS_AUTHOR NA
             WHERE NA.NEWS_ID = ALL_NEWS_STAT.NEWS_ID AND AUTHOR_ID = 1)
ORDER BY COMMENTS_COUNT DESC, MODIFICATION_DATE
