SELECT NEWS_ID, TITLE, SHORT_TEXT,
    FULL_TEXT, CREATION_DATE, MODIFICATION_DATE
FROM
    (SELECT APPROPRIATE_NEWS.*, ROWNUM R FROM
        (SELECT *
        FROM ((SELECT NEWS_ID, TITLE, SHORT_TEXT,
                    FULL_TEXT, CREATION_DATE, MODIFICATION_DATE, COMMENTS_COUNT
               FROM NEWS JOIN (SELECT NEWS_ID, COUNT(*) COMMENTS_COUNT
                               FROM COMMENTS
                               GROUP BY NEWS_ID) NEWS_STAT USING(NEWS_ID))
        UNION ALL
        (SELECT NEWS_ID, TITLE, SHORT_TEXT,
                    FULL_TEXT, CREATION_DATE, MODIFICATION_DATE, 0 COMMENTS_COUNT
        FROM NEWS
        WHERE NEWS_ID NOT IN(SELECT NEWS_ID
                             FROM COMMENTS))) ALL_NEWS_STAT
        WHERE EXISTS(SELECT * FROM NEWS_AUTHOR NA
                     WHERE NA.NEWS_ID = ALL_NEWS_STAT.NEWS_ID AND AUTHOR_ID = 1)
            AND NEWS_ID IN (SELECT NEWS_ID
                          FROM NEWS_TAG
                          WHERE TAG_ID IN (1, 2)
                          GROUP BY NEWS_ID
                          HAVING COUNT(*) = 2)
        ORDER BY COMMENTS_COUNT DESC, MODIFICATION_DATE) APPROPRIATE_NEWS) NEWS_PAGE
WHERE R BETWEEN 1 AND 2;
