SELECT R
FROM
    ((SELECT APPROPRIATE_NEWS.*, ROWNUM R FROM
        (SELECT *
        FROM ((SELECT NEWS_ID, TITLE, SHORT_TEXT,
                    FULL_TEXT, CREATION_DATE, MODIFICATION_DATE, COMMENTS_COUNT
               FROM NEWS JOIN (SELECT NEWS_ID, COUNT(*) COMMENTS_COUNT
                               FROM COMMENTS
                               GROUP BY NEWS_ID) NEWS_STAT USING(NEWS_ID))
        UNION ALL
        (SELECT NEWS_ID, TITLE, SHORT_TEXT,
                    FULL_TEXT, CREATION_DATE, MODIFICATION_DATE, 0 COMMENTS_COUNT
        FROM NEWS
        WHERE NEWS_ID NOT IN(SELECT NEWS_ID
                              FROM COMMENTS))) ALL_NEWS_STAT
        {0}{1}{2}{3}
        ORDER BY COMMENTS_COUNT DESC, MODIFICATION_DATE) APPROPRIATE_NEWS) NEWS_PAGE)
WHERE NEWS_ID = {4}
